### PR TITLE
copy editing, doc improvements

### PR DESCRIPTION
**Pull request by ngoldman**

### CODE REVIEW

**Comment by ngoldman** [comment]
Added some info about how to set up a PostGIS database for the cache.

@koopjs/dev let me know if this looks good & merge plz

**Comment by dmfenton** [comment]
Looks good. Just going to note that this relies on the promised work for :sparkles: Koop Zero :sparkles:

**Comment by slibby** [comment]
@dmfenton Why does this rely on Koop Zero? I am able to run Koop Sample App with just PostGIS and this repository.

**Comment by dmfenton** [comment]
I think I jumped to a false conclusion there. @dmfenton--

**Pull request merged**
